version: "2.1"
networks: {}
volumes:
  resin-data: {}
services:
  wifi_connect:
    build: ./wifi_connect
    network_mode: host
    labels:
      - io.balena.features.dbus: '1'
    cap_add:
      - NET_ADMIN
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS:"unis:path=/host/run/dbus/system_bus_socket"

  # MQTT broker
  mqtt:
    image: arm32v6/eclipse-mosquitto  
    restart: always
    network_mode: host
    ports:
      - "1883:1883"
  # POS interface
  pos-interface:
    build: ./pos-interface
    priviledged: true
    restart: always
    network_mode: host
    volumes:
      - 'resin-data:/data'
    depends_on:
      broker

  # more to be added